- name: Gather EC2 Facts
  ec2_instance_info:
    filters:
      "tag:Name": fortune
  register: ec2

- name: EC2 snapshot
  ec2_snapshot: 
    instance_id: "{{ item.instance_id }}"
    device_name: /dev/xvda
    description: Created with Ansible
    region: "{{ region }}"
    snapshot_tags:
      Name: fortune
  with_items: "{{ ec2.instances }}"
