- name: Gather EC2 Facts
  ec2_instance_info:
    filters:
      "tag:Name": fortune
      instance-state-name: "running"
  register: ec2

- name: EC2 snapshot
  ec2_snapshot: 
    instance_id: "{{ item.instance_id }}"
    device_name: /dev/xvda
    description: Created with Ansible
    region: "{{ region }}"
    snapshot_tags:
      Name: fortune
  with_items: "{{ ec2.instances }}"

- name: Gather EC2 Snapshot Info
  ec2_snapshot_info:
    filters:
      "tag:Name": fortune
  register: snap

#- debug: var=snap.snapshots

- name: AMI registration from EBS Snapshot
  ec2_ami:
    name: fortune
    state: present
    architecture: x86_64
    virtualization_type: hvm
    root_device_name: /dev/xvda
    device_mapping:
      - device_name: /dev/xvda
        volume_size: 8
        snapshot_id: "{{ snap.snapshots[0].snapshot_id }}"
        volume_type: gp2
        delete_on_termination: true
  register: ami

- name: Deploy EC2 Instance from Snapshot
  ec2:
    key_name: "{{ key_name }}"
    group: "{{ group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    wait_timeout: 500
    region: "{{ region }}"
    assign_public_ip: yes
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    count: 1
  with_items: ami.results
  register: ec2instance

- name: Terminate EC2 Instance
  ec2:
    state: 'absent'
    instance_id: "{{ item.instance_id }}"
    region: "{{ region }}"
  with_items: "{{ ec2.instances }}"












